# analysis_options.yaml

include:
  - package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - lib/generated/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.gr.dart
  errors:
    prefer_expression_function_bodies: ignore
    unawaited_futures: ignore

linter:
  rules:
    # --- Core style & safety rules ---
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_init_to_null: true
    file_names: true
    non_constant_identifier_names: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    require_trailing_commas: true
    sized_box_for_whitespace: true
    unnecessary_late: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    unawaited_futures: false
    avoid_catching_errors: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_shadowing_type_parameters: true
    avoid_types_on_closure_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    empty_statements: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_method_calls: true
    prefer_spread_collections: true
    provide_deprecation_message: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    type_init_formals: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    use_full_hex_values_for_flutter_colors: true
    use_rethrow_when_possible: true
    valid_regexps: true
